import { Inter } from 'next/font/google'
import './globals.css'
import { ThemeProvider } from '@/components/theme-provider'
import Header from '@/components/header'
import { Separator } from '@/components/ui/separator'
import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton
} from '@clerk/nextjs'

const inter = Inter({
  variable: '--font-inter',
  subsets: ['latin']
})

export const metadata = {
  title: 'Spyne',
  description: 'Generated by create next app'
}

export default function RootLayout ({ children }) {
  return (
    <ClerkProvider
      appearance={{
        baseTheme: 'dark'
      }}
    >
      <html lang='en' suppressHydrationWarning>
        <body className={`${inter.variable} ${inter.variable} antialiased`}>
          <ThemeProvider
            attribute='class'
            defaultTheme='dark'
            enableSystem
            disableTransitionOnChange
          >
            <Header />
            <Separator className='my-4' />
            <main className='min-h-screen mt-14'>{children}</main>
            <footer>
              <Separator />
              <div className='container mx-auto px-4 text-center'>
                <p>Made by Hamza</p>
              </div>
            </footer>
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  )
}
